### ISSUE TITLE
在程序内分发go-cqhttp的开源许可问题

### ISSUE THREAD

**Issue by mnixry** [XiaoMiku01/PaimonBot#11]
go-cqhttp采用AGPL开源许可，从理论上如果在程序内直接分发并打包go-cqhttp（无论是二进制或是源代码）
程序应当同样按照AGPL许可开源，这将要求任何人对该代码做的任何修改，都应该被开源

我个人在建议仓库中移除go-cqhttp相关的二进制文件，交由用户自行下载
这样可以规避AGPL许可的传染性问题

**Comment by XiaoMiku01** [comment]
已经删除，造成不便，望谅解！
