### ISSUE TITLE
撤回消息你是怎么获取message_id的?

### ISSUE THREAD

**Issue by lancer-wang** [XiaoMiku01/PaimonBot#12]
我看到是你是这样获取的
![image](https://user-images.githubusercontent.com/69783837/118576328-e218ac80-b7ba-11eb-8dc4-c120ae308573.png)
然后我复制了下,发现返回none
![image](https://user-images.githubusercontent.com/69783837/118576375-f9579a00-b7ba-11eb-9b50-355d43f807cc.png)
然后我去代码看了下,send方法没有返回东西,你是改了什么东西吗
![image](https://user-images.githubusercontent.com/69783837/118576450-2146fd80-b7bb-11eb-80cb-a1794af50b91.png)

**Comment by XiaoMiku01** [comment]
send方法返回的是一个对象，里面包含mid，你可以用pycharm，debug试试

**Comment by lancer-wang** [comment]
s实测这里加return才能获取到mid,kenen可能你用的send方法和我不是同一个
![image](https://user-images.githubusercontent.com/69783837/118584092-c7e5cb00-b7c8-11eb-9a78-59e9cba68db5.png)

![image](https://user-images.githubusercontent.com/69783837/118584122-daf89b00-b7c8-11eb-969b-c313596d1cbd.png)
