### ISSUE TITLE
"转换CQ码到MiraiGo Element时出现错误: %v 将忽略本段CQ码.", err

### ISSUE THREAD

**Issue by skp-093** [XiaoMiku01/PaimonBot#6]
这个要怎么解决啊

**Comment by XiaoMiku01** [comment]
具体哪个功能，其他功能是否正常，在哪个系统下运行的Linux还是windows？

**Comment by skp-093** [comment]
输入“周本””天赋“的时候会这样，系统是windows

**Comment by skp-093** [comment]
运行系统是windows。武器，天赋和周本会报这个错误，查武器资料的时候就直接没反应




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月7日(星期三) 晚上10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XiaoMiku01/PaimonBot] &quot;转换CQ码到MiraiGo Element时出现错误: %v 将忽略本段CQ码.&quot;, err (#6)





 
具体哪个功能，其他功能是否正常，在哪个系统下运行的Linux还是windows？

**Comment by XiaoMiku01** [comment]
把src/plugins/weapons/\_\_init\_\_.py内容替换成,然后重启bot.py
```python
from nonebot import on_command
from .get_data import get_weapon
from nonebot.adapters.cqhttp import Event, Bot, Message

wea = on_command('武器查询',aliases={'武器资料'})


@wea.handle()
async def _(bot: Bot, event: Event):
    name = str(event.get_message()).strip()
    re =await get_weapon(name)
    await wea.finish(message=Message(re))
```

然后把src/plugins/challenge/\_\_init\_\_.py内容贴出来让我看一下

**Comment by skp-093** [comment]
是替换完运行之后去复制吗from nonebot import on_endswith
from nonebot.adapters.cqhttp import Bot, Event, Message
from datetime import datetime
import os

tf = on_endswith('天赋')
we = on_endswith('武器')
zb = on_endswith('周本')

PATH = os.path.abspath('.')


@zb.handle()
async def _(bot: Bot, event: Event):
    await zb.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/zb.png]'))


@tf.handle()
async def _(bot: Bot, event: Event):
    mes = str(event.get_message())
    if '一' in mes:
        await tf.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/tf1.png]'))
    elif '二' in mes:
        await tf.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/tf2.png]'))
    elif '三' in mes:
        await tf.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/tf3.png]'))
    elif '四' in mes:
        await tf.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/tf4.png]'))
    elif '五' in mes:
        await tf.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/tf5.png]'))
    elif '六' in mes:
        await tf.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/tf6.png]'))
    else:
        day = str(datetime.now().isoweekday())
        if '明' in mes:
            if day == '7':
                day = '1'
                await tf.finish(
                    message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/tf{day}.png]'))
            else:
                day = str(int(day) + 1)
                await tf.finish(
                    message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/tf{day}.png]'))
        elif day != '7':
            await tf.finish(
                message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/tf{day}.png]'))
        else:
            await tf.finish(message='今天星期天所有副本都可以刷哦！')


@we.handle()
async def _(bot: Bot, event: Event):
    mes = str(event.get_message())
    if '一' in mes:
        await we.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/we1.png]'))
    elif '二' in mes:
        await we.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/we2.png]'))
    elif '三' in mes:
        await we.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/we3.png]'))
    elif '四' in mes:
        await we.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/we4.png]'))
    elif '五' in mes:
        await we.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/we5.png]'))
    elif '六' in mes:
        await we.finish(message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/we6.png]'))
    else:
        day = str(datetime.now().isoweekday())
        if '明' in mes:
            if day == '7':
                day = '1'
                await we.finish(
                    message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/we{day}.png]'))
            else:
                day = str(int(day) + 1)
                await we.finish(
                    message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/we{day}.png]'))
        elif day != '7':
            await we.finish(
                message=Message(f'[CQ:image,file=file://{PATH}/src/data/challenge/we{day}.png]'))
        else:
            await we.finish(message='今天星期天所有副本都可以刷哦！')




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月7日(星期三) 晚上10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XiaoMiku01/PaimonBot] &quot;转换CQ码到MiraiGo Element时出现错误: %v 将忽略本段CQ码.&quot;, err (#6)





 
把src/plugins/weapons/__init__.py内容替换成
 from nonebot import on_command from .get_data import get_weapon from nonebot.adapters.cqhttp import Event, Bot, Message wea = on_command('武器查询',aliases={'武器资料'}) @wea.handle() async def _(bot: Bot, event: Event):     name = str(event.get_message()).strip()     re =await get_weapon(name)     await wea.finish(message=Message(re))
 
然后把src/plugins/challenge/__init__.py内容贴出来让我看一下

**Comment by XiaoMiku01** [comment]
哦，这个bug今天已经修复了。你重新下载最新的项目替换整个src文件夹，重新运行俩个就行了

**Comment by skp-093** [comment]
噢噢，好的，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月7日(星期三) 晚上10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XiaoMiku01/PaimonBot] &quot;转换CQ码到MiraiGo Element时出现错误: %v 将忽略本段CQ码.&quot;, err (#6)





 
哦，这个bug今天已经修复了。你重新下载最新的项目替换整个src文件夹，重新运行俩个就行了

**Comment by skp-093** [comment]
可以问下大佬怎么挂在服务器上吗？

**Comment by skp-093** [comment]
>

**Comment by XiaoMiku01** [comment]
clone 这个仓库，运行linux版本的cqhttp,装好依赖库运行bot.py就行了

**Comment by skp-093** [comment]
好的，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月7日(星期三) 晚上11:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [XiaoMiku01/PaimonBot] &quot;转换CQ码到MiraiGo Element时出现错误: %v 将忽略本段CQ码.&quot;, err (#6)





 
clone 这个仓库，运行linux版本的cqhttp,装好依赖库运行bot.py就行了
