### ISSUE TITLE
challenge插件bug反馈

### ISSUE THREAD

**Issue by Ruby280255768** [XiaoMiku01/PaimonBot#8]
周六时查询明日天赋/武器均无反应，后台日志有报错，应该是没有对应tf7.png和we7.png的原因，此外查询周日（星期天）天赋/武器命令也没有对应的判断语句，查询都是返回周六的图片

**Comment by XiaoMiku01** [comment]
因为周日副本全开啊，我就没管了。。。

**Comment by Ruby280255768** [comment]
有时候会忘记今天是周六。。。不过也确实不是什么大问题就是了

**Comment by XiaoMiku01** [comment]
有空加上吧，先咕咕咕了
